F08-Edit-Laptop
aldhisttd/2023_5pagia_laptop_fe pull request #1
Opened 2023-12-25 03:15 UTC by Fazamazaya

![Screenshot 2023-12-25 095456](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131894/a348ff73-6251-43a8-8900-c1b5fd2f5d6c)
@aldhi88

2023-12-25 18:13 UTC, Fazamazaya commented
![Screenshot 2023-12-26 004845](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131894/52cd9c04-894b-4bcc-8f83-11d9c4296398)
izin pak,
@aldhisttd 
@aldhi88

2023-12-26 05:46 UTC, aldhi88 requested changes
@Fazamazaya , payload sudah benar

harusnya scirpt kamu gak jalan, di script kamu ada ambil url variabel dan kamu call api dengan payload kode. sementara di screenshoot kamu gak ada url var nya

dan harusnya ada call api untuk generate data kategori dan merek ke component select-option

2023-12-26 05:46 UTC, aldhi88 commented on admin/script/laptop_edit.js
> +                console.log(data);
hapus @Fazamazaya

2023-12-26 05:46 UTC, aldhi88 commented on admin/script/laptop_edit.js
> +                var data = response.body.data[0];
hapus index 0 nya @Fazamazaya

2023-12-26 16:09 UTC, Fazamazaya commented
![Screenshot 2023-12-26 230108](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131894/9503fe8f-b2b8-42bf-8799-9e5e7283d365)
![Screenshot 2023-12-26 230122](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131894/3cc5ac43-e855-4699-8eb5-a46cfeeed1dc)

2023-12-27 04:26 UTC, aldhi88 requested changes
@Fazamazaya , logic nya :

1. ketika load halaman edit lakukan parsing data kategori dan merek terlebih dahulu
2. lalu ambil url var dan jadikan payload ketika hit api Read by ID
3. setelah success, ambil hasil respon dan parsing value2 ke form
4. untuk kategori dan merek kamu tinggal tambahkan selected di option nya sesuai data edit, jangan di empty kan lagi, nnti list kategori dan mereknya jadi kosong
5. setelah itu call api Update ketika form di submit.

2023-12-27 04:26 UTC, aldhi88 commented on admin/script/laptop_edit.js
> +                var data = response.body.data[0];
@Fazamazaya ini kok belum dihapus

2023-12-27 05:56 UTC, Fazamazaya commented on admin/script/laptop_edit.js
> +                var data = response.body.data[0];
kalau gak pakai itu, gak muncul value nya pak @aldhi88 @aldhisttd

2023-12-28 15:15 UTC, Fazamazaya commented
![Screenshot 2023-12-28 215747](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131894/211c3489-6dd5-46c8-bf98-8d366e169e84)
![Screenshot 2023-12-28 215832](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131894/fb375254-e7f1-4938-a4ac-13c9e511fb14)
@aldhi88 @aldhisttd

2023-12-29 04:10 UTC, aldhi88 approved these changes

2024-01-17 02:02 UTC, merged