F02 Edit Kategori
aldhisttd/2023_5pagia_laptop_fe pull request #11
Opened 2024-01-03 16:38 UTC by Fazamazaya

![Screenshot 2024-01-03 232632](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131894/4db7ec3c-2e21-4187-8745-ae997a9ff633)
![Screenshot 2024-01-03 232744](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131894/f29f55a0-9672-4be1-981b-28c095f7f5a8)
@aldhi88 @aldhisttd

2024-01-04 12:15 UTC, aldhi88 requested changes

2024-01-04 12:15 UTC, aldhi88 commented on admin/kategori_edit.php
> +        <form action="" method="POST" id="formKategori">
@Fazamazaya method dan action hapus

2024-01-04 12:15 UTC, aldhi88 commented on admin/kategori_edit.php
> +                <button class="btn btn-danger" type="reset">Reset</button>
@Fazamazaya ganti jadi tombol link ke data kategori

2024-01-04 14:17 UTC, Fazamazaya commented
![Screenshot 2024-01-04 211337](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131894/659c4b95-3385-43bc-8f1f-942db05fc6c4)
![Screenshot 2024-01-04 211355](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131894/59ac014c-b751-4d07-895b-cd440daeb219)
@aldhi88 @aldhisttd

2024-01-04 14:24 UTC, aldhi88 requested changes

2024-01-04 14:24 UTC, aldhi88 commented on admin/kategori_edit.php
> +                <a href="?page=kategori_data" class="btn btn-danger">Batal</a>
@urlnya yg lengkap, pake variabel `host_fe` seperti redirect di js nya @Fazamazaya

2024-01-04 14:43 UTC, Fazamazaya commented on admin/kategori_edit.php
> +                <a href="?page=kategori_data" class="btn btn-danger">Batal</a>
@aldhi88 sudah pak

2024-01-05 02:42 UTC, aldhi88 requested changes

2024-01-05 02:42 UTC, aldhi88 commented on admin/kategori_edit.php
> +                <a href="http://localhost/2023_5pagia_laptop_fe/admin/?page=kategori_data" class="btn btn-danger">Batal</a>
@Fazamazaya pake variable yg di env nya kok kyk gini , di lokal saya ya gak jalan donk

2024-01-05 03:22 UTC, Fazamazaya commented on admin/kategori_edit.php
> +                <a href="http://localhost/2023_5pagia_laptop_fe/admin/?page=kategori_data" class="btn btn-danger">Batal</a>
@aldhi88 @aldhisttd sudah direvisi pak

2024-01-05 03:38 UTC, aldhi88 requested changes
@Fazamazaya jgn pake elemen `<a></a>`, pake button aja, trus pake event onclick di elemen button nya langsung jadi gak perlu script lagi. `onclick=redirect_ke_halaman_data`, 
test dulu baru push

2024-01-05 03:59 UTC, aldhi88 approved these changes

2024-01-17 02:01 UTC, merged