F01-input-kategori
aldhisttd/2023_5pagia_laptop_fe pull request #14
Opened 2024-01-04 15:53 UTC by viggo21

<img width="539" alt="irhas" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129132404/b377ceca-7bd4-4f97-a129-3987da24d57b">

 ini tugas saya pak @aldhi88 , sudah saya pr ulang pak

2024-01-05 02:47 UTC, aldhi88 requested changes
@viggo21 screenshoot salah, harusnya gak seperti itu, baca lagi cara run aplikasinya.

2024-01-05 03:55 UTC, viggo21 commented
> @viggo21 screenshoot salah, harusnya gak seperti itu, baca lagi cara run aplikasinya.

<img width="800" alt="irhas2" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129132404/530ca43a-ccb7-422c-b098-1c27b3866c6e">
apakah sudah bener pak screenshot an nya pak @aldhi88 ?

2024-01-05 04:41 UTC, viggo21 commented
pak apakah begini ss an nya ?
![image](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129132404/051c2f3c-1f44-4d09-af91-bcd3e18487d1)
@aldhi88

2024-01-08 04:59 UTC, aldhi88 approved these changes

2024-01-08 04:59 UTC, merged