F05-Edit-Merek
aldhisttd/2023_5pagia_laptop_fe pull request #15
Opened 2024-01-04 16:30 UTC by MahmudAlburozi12

<img width="580" alt="mahmud3" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129132311/61f98565-ca81-4e6e-8bb5-c99725ea52f7">
<img width="543" alt="mahmud4" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129132311/cf12353c-f1ea-4d2f-8ae5-4cb7753a22c4">

izin pak ini revisiannya pak @aldhi88 pr baru pak

2024-01-05 02:46 UTC, aldhi88 requested changes
@MahmudAlburozi12 kenapa ada file yg di hapus, dan screenshoot nya harusnya gak seperti ini

2024-01-08 04:54 UTC, aldhi88 requested changes

2024-01-08 04:54 UTC, aldhi88 commented on admin/menu_edit.php
@MahmudAlburozi12 form nya terlalu lebar, kecilkan

2024-01-09 00:34 UTC, MahmudAlburozi12 commented on admin/menu_edit.php
udah saya kecilkan pak pakai col-md-5

2024-01-17 01:49 UTC, aldhi88 approved these changes

2024-01-17 01:49 UTC, merged