F07-input-laptop
aldhisttd/2023_5pagia_laptop_fe pull request #16
Opened 2024-01-04 16:52 UTC by Yutagaru

<img width="733" alt="imam" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131764/b0e19985-8384-42da-bb4d-6cc19c2b87f0">

revisi nya pak @aldhi88

2024-01-05 02:45 UTC, aldhi88 requested changes
@Yutagaru screenshoot nya harusnya gak seperti ini, ganti

2024-01-07 17:37 UTC, Yutagaru commented
![image](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131764/6866afb2-0ccc-4933-93c7-6bebf515edc4)
screenshot baru nya pak

2024-01-08 04:43 UTC, aldhi88 approved these changes

2024-01-08 04:43 UTC, aldhi88 commented on admin/laptop_create.php
@Yutagaru form nya kecilkan terlalu lebar, pake col-md-5

2024-01-08 04:43 UTC, aldhi88 requested changes
@Yutagaru kecilkan form nya

2024-01-08 15:59 UTC, aldhi88 approved these changes

2024-01-08 15:59 UTC, merged