F03-Tabel-Data-Delete-kategori
aldhisttd/2023_5pagia_laptop_fe pull request #17
Opened 2024-01-04 17:06 UTC by oktihryn123

<img width="801" alt="okti" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131929/ec7ed50b-d6fd-4d95-a641-57212e43bbc8">
<img width="799" alt="okti1" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131929/657e7826-5d76-4ca6-9627-6665e867a80d">
<img width="801" alt="okti2" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131929/fb637bc7-eaa4-469f-b7be-d6e210fcfc3c">
@aldhi88

2024-01-05 02:44 UTC, aldhi88 requested changes
@oktihryn123 screen shoot nya ganti, harusnya ada menunya

2024-01-05 03:28 UTC, oktihryn123 commented
> @oktihryn123 screen shoot nya ganti, harusnya ada menunya

menu apa maksudnya pak?

2024-01-05 03:50 UTC, oktihryn123 commented
> @oktihryn123 screen shoot nya ganti, harusnya ada menunya

<img width="797" alt="okti4" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131929/56af88f6-3845-461b-975d-09cb0e20454a">
<img width="799" alt="okti5" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131929/90af9746-db97-4801-9b99-087ad978953a">
<img width="803" alt="okti6" src="https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131929/5d40030d-3242-4b53-8d31-7de56bc95ec2">

apakah seperti pak screenshot nya @aldhi88 ?

2024-01-08 04:56 UTC, aldhi88 approved these changes

2024-01-08 04:56 UTC, merged