F09-Tabel-Data-Delete-Laptop
aldhisttd/2023_5pagia_laptop_fe pull request #4
Opened 2023-12-26 17:09 UTC by agungsyhptra

![Screenshot (135)](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131946/b8f193c9-0f73-4b90-abff-96889cad785a)
![Screenshot (136)](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131946/45147c56-39d6-46fe-abd5-e6c9977cdb59)
@aldhi88

2023-12-27 04:05 UTC, aldhi88 requested changes

2023-12-27 04:05 UTC, aldhi88 commented on admin/script/laptop_data.js
> +                            <img src="../assets/img/` +
ini mengarah ke alamat BE donk, file nya kan di upload ke project backend @agungsyhptra

2023-12-27 04:05 UTC, aldhi88 commented on admin/script/laptop_data.js
> +                        datalaptop[i].kode_kategori +
ini harusnya nama dari kategori nya yg di cetak, bukan kode nya @agungsyhptra

2023-12-27 04:05 UTC, aldhi88 commented on admin/script/laptop_data.js
> +                        datalaptop[i].kode_merek +
@agungsyhptra , sama seperti kategori

2023-12-27 04:05 UTC, aldhi88 commented on admin/script/laptop_data.js
> +                                <a class="text-light" href="../obat_edit/menu_edit.php?kode=` +
@agungsyhptra , gak seperti ini URL nya, perhatikan baik2 ketentuan URL kita

2023-12-27 04:05 UTC, aldhi88 commented on admin/script/laptop_data.js
> +                        alert(response.msg);
@agungsyhptra , setelah delete success, tampil pesan lalu refresh table nya

2023-12-28 11:14 UTC, agungsyhptra commented on admin/script/laptop_data.js
> +                        datalaptop[i].kode_kategori +
pak saya ga paham maksudnya pak, bukannya ini harus sesuai dgn api spec atau gmana pak ?? kalau yg sesuai api spec kode kategori dan kode merek pak 
![Screenshot 2023-12-28 181313](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129131946/be821503-a075-434f-b2ca-77862ad4e9c8)

2024-01-03 01:37 UTC, aldhi88 requested changes

2024-01-03 01:37 UTC, aldhi88 commented on admin/laptop_data.php
@agungsyhptra ikuti kategori create

2024-01-03 08:31 UTC, agungsyhptra commented on admin/laptop_data.php
di bagian mananya saya harus ikuti pak? @aldhi88

2024-01-05 02:59 UTC, aldhi88 requested changes

2024-01-05 02:59 UTC, aldhi88 commented on admin/script/laptop_data.js
> +                        '<td>' + laptopList[i].kategori + '</td>' +
@agungsyhptra kategori dan merek yg tampil adalah namanya, lihat payload respon untuk nama nya sperti apa, ini gak sesuai api spec

2024-01-05 02:59 UTC, aldhi88 commented on admin/script/laptop_data.js
> +    function handleDeleteButtonClick() {
@agungsyhptra kyknya ini gak perlu di dalam function, keluarkan aja

2024-01-08 04:46 UTC, aldhi88 commented on admin/script/laptop_data.js
> +                        datalaptop[i].kode_kategori +
@agungsyhptra , di FE data nya di tampilkan dalam bentuk tabel, bagian kategori ya nama nya donk, jgn kode nya

2024-01-08 04:49 UTC, aldhi88 requested changes

2024-01-08 04:49 UTC, aldhi88 commented on admin/script/laptop_data.js
> +                        '<td><img src="' + laptopList[i].gambar + '" width="100" /></td>' +
@agungsyhptra gak tampil gambarnya klo kyk gini

2024-01-08 04:49 UTC, aldhi88 commented on admin/script/laptop_data.js
> +                        '<a class="btn btn-primary" href="index.php?page=laptop_edit&kode=' + laptopList[i].kode + '">Edit</a>' +
@agungsyhptra , kykya gak usah ada `index.php` langsung aja ?page=blabla

2024-01-17 03:17 UTC, merged