F04 Input Merek
aldhisttd/2023_5pagia_laptop_fe pull request #8
Opened 2024-01-03 03:58 UTC by ismiati20

![Aplikasi Katalog Laptop - Google Chrome 1_3_2024 9_42_25 AM](https://github.com/aldhisttd/2023_5pagia_laptop_fe/assets/129134113/0c007c98-f9a0-4418-950a-2a77377ef992)

2024-01-04 13:40 UTC, aldhi88 requested changes

2024-01-04 13:40 UTC, aldhi88 commented on admin/merek_create.php
> +            <form id="MerekCreate" action="" method="POST" enctype="multipart/form-data">
@ismiati20 pake atribute id aja, yg lain hapus

2024-01-04 14:20 UTC, ismiati20 commented on admin/merek_create.php
> +            <form id="MerekCreate" action="" method="POST" enctype="multipart/form-data">
baikkk pakk @aldhi88

2024-01-08 04:52 UTC, aldhi88 requested changes

2024-01-08 04:52 UTC, aldhi88 commented on admin/merek_create.php
@ismiati20 samakan dengan format  code di dashboard.html

2024-01-17 02:52 UTC, aldhi88 approved these changes

2024-01-17 02:52 UTC, merged